### ISSUE TITLE
Add https for the site http://www.midica.org/ and redirect from http to https

### ISSUE THREAD

**Issue by dhammma** [truj/midica.org#2]
When I see something without https I start thinking it's something old and not actual. I think that it can help increase trust to this project from newcomers accidentally visited the project first time

**Comment by truj** [comment]
Thank you for your suggestion. I totally understand your concerns.
But anyway, I don't plan to buy an SSL certificate soon.
Maybe some day in the future...

**Comment by dhammma** [comment]
But... in 2023 SSL certificates are free - you can use let's encrypt, or self-managed certificates of your hosting platform

**Comment by truj** [comment]
Sorry for the late reply, I currently have issues with email notifications...
I didn't know abut Lets Encrypt, and according to my provider's website it should be possible to use it.
I'll try to set it up as soon as I have time.
Thanks again for the suggestion.

**Comment by truj** [comment]
Switched to https, and configured the 301 redirect.
I still have to check/update links and readmes in both projects, so I'll leave this issue open until that's done.

**Comment by truj** [comment]
Everything is up to date now, so this can be closed.
